version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqllab
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "32001:3306"
    volumes:
      - mysqllab_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  jupyterlab:
    container_name: jupyterlab
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - 'mysql'
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token=''


volumes:
  mysqllab_data: